/*
 * POST /users should create a new user in DB:
 * To create a user, you must specify an email and a password
 * If the email is missing, return an error Missing email with a status code 400
 * If the password is missing, return an error Missing password with a status code 400
 * If the email already exists in DB, return an error Already exist with a status code 400
 * The password must be stored after being hashed in SHA1
 * The endpoint is returning the new user with only the email and the id
 * (auto generated by MongoDB) with a status code 201
 * The new user must be saved in the collection users:
 * email: same as the value received
 * password: SHA1 value of the value received
 */
import user from '../utils/user';
import crypto from 'crypto';

const UsersController = {
  postNew: (req, res) => {
    if (!('email' in req.body)) {
      res.status(400).send(new Error('Missing email'));
    }
    else if (!('password' in req.body)) {
      res.status(400).send(new Error('Missing password'));
    }
    else {
      try {
        const existingUser = user.search(req.body['email'])
          .catch(err => console.error(err));
        if (existingUser !== -1) {
          res.status(400).send(new Error('Already exist'));
        } else {
          const newUser = user.addUser(req.body['email'], req.body['password'])
            .catch((err) => console.error('Mayday mayday, ', err));
          res.status(201).json(newUser);
	}
      } catch (err) {
        console.error(err);
      }
    }
  }
};

module.exports = UsersController;
